name = "json"
description = "An Ada 2012 library for parsing JSON"
version = "5.0.3"
website = "https://github.com/onox/json-ada"
licenses = "Apache-2.0"
tags = ["json"]

executables = ["pretty_print"]

project-files = ["json.gpr", "json_pretty_print.gpr"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]
